source "https://rubygems.org"

gem "opal", "~> 0.11"
gem "gibier", "0.8.16"
gem "opal-router",    github: "adambeynon/opal-router"
gem "opal-haml",      github: "opal/opal-haml"
gem "opal-websocket", github: "youchan/opal-websocket"
gem "hyalite"

